- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart notesapp
  ansible.builtin.service:
    name: notesapp
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
